type RiskPoint = { label: string; value: number };

export function RiskTimeline({ data }: { data: RiskPoint[] }) {
  const width = 640, height = 210, pad = 28;
  const points = data.map((point, index) => `${pad + (index * (width - pad * 2)) / Math.max(data.length - 1, 1)},${height - pad - (point.value * (height - pad * 2)) / 100}`).join(" ");
  return <div className="overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="min-w-[520px] w-full" aria-label="Risk forecast timeline">{[0, 25, 50, 75, 100].map(value => <g key={value}><line x1={pad} x2={width - pad} y1={height - pad - value * (height - pad * 2) / 100} y2={height - pad - value * (height - pad * 2) / 100} stroke="#e2e8f0" /><text x="0" y={height - pad - value * (height - pad * 2) / 100 + 4} fontSize="10" fill="#64748b">{value}</text></g>)}<polyline points={points} fill="none" stroke="#38bdf8" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{data.map((point, index) => { const [x, y] = points.split(" ")[index].split(","); return <g key={point.label}><circle cx={x} cy={y} r="4" fill="#0f172a" stroke="#7dd3fc" strokeWidth="3"/><text x={x} y={height - 7} textAnchor="middle" fontSize="10" fill="#64748b">{point.label}</text></g>; })}</svg></div>;
}

export function StageDistribution({ stages }: { stages: { label: string; value: number; color: string }[] }) { return <div className="space-y-4">{stages.map(stage => <div key={stage.label}><div className="mb-1 flex justify-between text-sm"><span className="text-slate-600">{stage.label}</span><span className="font-semibold text-slate-800">{stage.value}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full" style={{ width: `${stage.value}%`, background: stage.color }} /></div></div>)}</div>; }
export function FeatureBars({ features }: { features: { name: string; value: number; note: string }[] }) { const maximum = Math.max(...features.map(feature => feature.value), 1); return <div className="space-y-4">{features.map(feature => <div key={feature.name}><div className="mb-1 flex items-baseline justify-between gap-3"><span className="text-sm font-medium text-slate-700">{feature.name}</span><span className="text-xs text-slate-500">{feature.note}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-cyan-500" style={{ width: `${feature.value / maximum * 100}%` }} /></div></div>)}</div>; }
